=== ViktorijaBerlanuk96/XML/newXmlSchema.xsd
<?xml version="1.0"?>

<xs:schema version="1.0" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="MujNabytek">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="hornibox">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="logo"/>
              <xs:element type="xs:string" name="moto"/>
              <xs:element name="kosik">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="ikona"/>
                    <xs:element type="xs:integer" name="pocetKusu"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="levybox">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="menu">
                <xs:complexType mixed="true">
                  <xs:sequence>
                    <xs:element name="kategorie">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Loznice">
                            <xs:complexType mixed="true">
                              <xs:sequence>
                                <xs:element type="xs:string" name="Postele"/>
                                <xs:element type="xs:string" name="Skrine"/>
                                <xs:element type="xs:string" name="NocniStolky"/>
                                <xs:element type="xs:string" name="Komody"/>
                              </xs:sequence>
                              <xs:attribute type="xs:string" name="hover"/>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="Obyvak">
                            <xs:complexType mixed="true">
                              <xs:sequence>
                                <xs:element name="SedaciSoupravy">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute type="xs:boolean" name="vybrano"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element type="xs:string" name="Konferencnistolky"/>
                                <xs:element type="xs:string" name="ObyvaciSteny"/>
                                <xs:element type="xs:string" name="Policky"/>
                                <xs:element type="xs:string" name="Knihovna"/>
                              </xs:sequence>
                              <xs:attribute type="xs:boolean" name="vybrano"/>
                              <xs:attribute type="xs:boolean" name="hover"/>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="Kuchyn">
                            <xs:complexType mixed="true">
                              <xs:sequence>
                                <xs:element type="xs:string" name="KuchynskaLinka"/>
                                <xs:element type="xs:string" name="JidelniStul"/>
                              </xs:sequence>
                              <xs:attribute type="xs:boolean" name="hover"/>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="Koupelna">
                            <xs:complexType mixed="true">
                              <xs:sequence>
                                <xs:element type="xs:string" name="SkrinPodUmyvadlo"/>
                                <xs:element type="xs:string" name="VesakNaRucniky"/>
                                <xs:element type="xs:string" name="RohovyStojan"/>
                              </xs:sequence>
                              <xs:attribute type="xs:boolean" name="hover"/>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="Predsin">
                            <xs:complexType mixed="true">
                              <xs:sequence>
                                <xs:element type="xs:string" name="Botniky"/>
                                <xs:element type="xs:string" name="Vesaky"/>
                              </xs:sequence>
                              <xs:attribute type="xs:boolean" name="hover"/>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="Zahrada">
                            <xs:complexType mixed="true">
                              <xs:sequence>
                                <xs:element type="xs:string" name="VenkovniSoupravy"/>
                                <xs:element type="xs:string" name="Slunecniky"/>
                              </xs:sequence>
                              <xs:attribute type="xs:boolean" name="hover"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="background"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="sirka"/>
            <xs:attribute type="xs:string" name="vyska"/>
            <xs:attribute type="xs:string" name="ohraniceni"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="pravybox">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="aktualniNabytek">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="nazev"/>
                    <xs:element name="fotka">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="sirka"/>
                            <xs:attribute type="xs:string" name="vyska"/>
                            <xs:attribute type="xs:string" name="zobrazeni"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="popis">
                      <xs:complexType mixed="true">
                        <xs:sequence>
                          <xs:element type="xs:string" name="material"/>
                          <xs:element type="xs:string" name="barva"/>
                          <xs:element type="xs:string" name="rozmery"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="cena">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:boolean" name="sleva"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:string" name="skladem"/>
                    <xs:element type="xs:integer" name="kusu"/>
                    <xs:element type="xs:string" name="pridat"/>
                    <xs:element type="xs:string" name="odebrat"/>
                    <xs:element name="social">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:boolean" name="like"/>
                          <xs:element type="xs:boolean" name="share"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="dalsiNabidka">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="okenko" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="fotka">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:string" name="sirka"/>
                                  <xs:attribute type="xs:string" name="vyska"/>
                                  <xs:attribute type="xs:string" name="zobrazeni"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element type="xs:string" name="nazev"/>
                          <xs:element name="cena">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:boolean" name="sleva"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:integer" name="id"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:boolean" name="onresize"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ViktorijaBerlanuk96/XML/xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="transformace.xsl" type="text/xsl"?>
<MujNabytek onresize="false" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="newXmlSchema.xsd">
    <hornibox>
        <logo>logo.png</logo>
        <moto>Nábytek pro vás</moto>
        <kosik>
            <ikona>kosik.png</ikona>
            <pocetKusu>2</pocetKusu>
        </kosik>
    </hornibox>
    
    <levybox sirka="35px" vyska="60px" ohraniceni="1px solid black">
        <menu background="light blue">Menu
            <kategorie>
                <Loznice hover="true">Ložnice
                    <Postele>Postele</Postele>
                    <Skrine>Skříně</Skrine>
                    <NocniStolky>Noční stolky</NocniStolky>
                    <Komody>Komody</Komody>
                </Loznice>
                <Obyvak vybrano="true" hover="false">Obývák
                    <SedaciSoupravy vybrano="true">Sedací soupravy</SedaciSoupravy>
                    <Konferencnistolky>Konferenční stolky</Konferencnistolky>
                    <ObyvaciSteny>Obývací stěny</ObyvaciSteny>
                    <Policky>Police</Policky>
                    <Knihovna>Knihovny</Knihovna>
                </Obyvak>
                <Kuchyn hover="false">Kuchyň
                    <KuchynskaLinka>Kuchyňská linka</KuchynskaLinka>
                    <JidelniStul>Jídelní stůl</JidelniStul>
                </Kuchyn>
                <Koupelna hover="false">Koupelna
                    <SkrinPodUmyvadlo>Sříně pod umyvadlo</SkrinPodUmyvadlo>
                    <VesakNaRucniky>Věšáky</VesakNaRucniky>
                    <RohovyStojan>Rohový stojan na věci</RohovyStojan>  
                </Koupelna>
                <Predsin hover="false">Předsíň
                    <Botniky>Botníky</Botniky>
                    <Vesaky>Věšáky</Vesaky>
                </Predsin>
                <Zahrada hover="false">Zahrada
                    <VenkovniSoupravy>Venkovní soupravy</VenkovniSoupravy>
                    <Slunecniky>Slunečníky</Slunecniky>    
                </Zahrada>
            </kategorie>
        </menu> 
    </levybox> 
        
    <pravybox>
        <aktualniNabytek>
            <nazev>Sedací souprava Indilia</nazev>
            <fotka sirka="460px" vyska="393px" zobrazeni="plne">obrazek.png</fotka>
            <popis>
                Do všech malých obývacích pokojů, ale i dětských nebo studentských pokojů se bude hodit naše nová a praktická sedací souprava Indilia, která vám nezabere ani centimetr místa navíc.
                <material>čalounění</material>
                <barva>černá</barva>
                <rozmery>
                    šířka:   215 cm
                    výška:   85  cm
                    hloubka: 135 cm
                </rozmery>
            </popis>
            <cena sleva="false">6 990 Kč</cena>
            <skladem>Dostupné skladem</skladem>
            <kusu>1</kusu>
            <pridat>přidat do košíku</pridat>
            <odebrat>odebrat z košíku</odebrat>
            <social>
                <like>true</like>
                <share>true</share>
            </social>
        </aktualniNabytek>
        
        <dalsiNabidka>
            <okenko id="1">
                <fotka  sirka="195px" vyska="220px" zobrazeni="mini">obrazek.png</fotka>
                <nazev>Křeslo Boss</nazev>
                <cena sleva="false">5 890 Kč</cena>
            </okenko>
            
            <okenko id="2">
                <fotka sirka="195px" vyska="220px" zobrazeni="mini">obrazek.png</fotka>
                <nazev>Sedací souprava Karol</nazev>
                <cena sleva="false">9 999 Kč</cena>
            </okenko>
            
            <okenko id="3">
                <fotka sirka="195px" vyska="220px" zobrazeni="mini">obrazek.png</fotka>
                <nazev>Destiny model sedací souprava</nazev>
                <cena sleva="true">4 600 Kč</cena>
            </okenko>
            
            <okenko id="4">
                <fotka sirka="195px" vyska="220px" zobrazeni="mini">obrazek.png</fotka>
                <nazev>Křeslo Alžběta</nazev>
                <cena sleva="false">6 750 Kč</cena>
            </okenko>
            
            <okenko id="5">
                <fotka sirka="195px" vyska="220px" zobrazeni="mini">obrazek.png</fotka>
                <nazev>Sedací souprava Amel</nazev>
                <cena sleva="false">7 200 Kč</cena>
            </okenko>
        </dalsiNabidka>
    </pravybox>
</MujNabytek>
